server:
  port: 8086

spring:
  application:

    name: cs-message
  main:
    allow-bean-definition-overriding: true
eureka:
  client:

    service-url:
      defaultZone: http://localhost:8080/eureka
feign:
  hystrix:

    enabled: false
