server:
  port: 9100

spring:
  application:
    name: zuul
  main:
    allow-bean-definition-overriding: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/pinyougoudb
    username: root
    password: root
  redis:
    port: 6379
    database: 0
    host: 127.0.0.1
    password:
    jedis:
      pool:
        max-active: 20
        max-wait: 9000ms
        max-idle: 20
        min-idle: 0
    timeout: 5000ms
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
mybatis:
  #mybatisxml文件的地址
  mapper-locations: classpath:mapper/*.xml
  #showsql
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
zuul:
  routes:
    api-a:
      path: /api-a/**
      serviceId: cs-home
    api-b:
      path: /api-b/**
      serviceId: cs-message
    api-c:
      path: /api-c/**
      serviceId: cs-search
    api-d:
      path: /api-d/**
      serviceId: cs-service