server:
  port: 8084

spring:
  application:

    name: cs-search

eureka:
  client:
    #eureka
    service-url:
      defaultZone: http://localhost:8080/eureka
feign:
  hystrix:

    enabled: true

