server:
  port: 8080

spring:
  application:
    #应用名称 这个很重要，这在以后的服务与服务之间相互调用一般都是根据这个name
    name: eureka-server
eureka:
  client:
    #在默认情况下erureka server也是一个eureka client ,必须要指定一个 server，这样会报错
    #注册到eureka:关闭  false表示不向注册中心注册自己
    register-with-eureka: false
    #获取注册列表：关闭 false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    fetch-registry: false
    #配置eureka服务地址
    #默认地址为：http://localhost:8761/eureka/
    service-url:
      defaultZone: http://localhost:8080/eureka
